name: Weekly development breakdown stats
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update the stats
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 25cba6fd287a470c18f5c2b31dee6c2b
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
